import fs from "node:fs"
import path from "node:path"
import type { McpClientConfig } from "@shared/types/McpClientConfig"

/**
 * One config file per session, not one per app.
 *
 * A single fixed `apiweave.json` was a live-token hazard twice over. Two
 * sessions launched at once raced on the same path, so the second launch
 * rewrote the token the first one had already been handed — and since the
 * bridge mints a fresh token per run, the first agent's config could stop
 * authenticating mid-session. Worse, one shared file has no owner, so nothing
 * could ever delete it: a bearer token good for every whitelisted MCP tool sat
 * in userData until the next launch overwrote it.
 *
 * Keying the name on the session id gives the file exactly one owner and one
 * lifetime, which is what makes {@link deleteAgentMcpConfig} and the startup
 * {@link sweepAgentMcpConfigs} possible at all.
 */
const CONFIG_PREFIX = "apiweave-mcp-"
const CONFIG_SUFFIX = ".json"

export function agentMcpConfigFilename(sessionId: string): string {
  return `${CONFIG_PREFIX}${sanitizeSessionId(sessionId)}${CONFIG_SUFFIX}`
}

/**
 * Write the MCP config a launched agent is pointed at, and return its path.
 *
 * The obvious implementation of "wire up MCP" is to drop an `.mcp.json` into
 * the working directory. That directory is a git repository, and the file holds
 * a bearer token good for every whitelisted MCP tool — so it goes into
 * APIWeave's own userData instead, and the agent is given the path. The token
 * stays out of argv too, where any process listing on the machine could read
 * it.
 *
 * `0o600` on POSIX for the same reason. Windows has no chmod equivalent worth
 * emulating here; userData is already per-user there.
 */
export function writeAgentMcpConfig(configDir: string, config: McpClientConfig, sessionId: string): string {
  fs.mkdirSync(configDir, { recursive: true, mode: 0o700 })
  const filePath = path.join(configDir, agentMcpConfigFilename(sessionId))
  const contents = {
    mcpServers: {
      apiweave: {
        type: "http",
        url: config.url,
        headers: { Authorization: `Bearer ${config.token}` },
      },
    },
  }
  fs.writeFileSync(filePath, `${JSON.stringify(contents, null, 2)}\n`, { encoding: "utf8", mode: 0o600 })
  return filePath
}

/**
 * Drop one session's config. Best-effort by design: the caller is a terminal
 * state transition, and a session that already ended must not fail to be
 * recorded because a scratch file was already gone (or is held open on
 * Windows). Whatever survives here is reclaimed by the next startup sweep.
 */
export function deleteAgentMcpConfig(configDir: string, sessionId: string): boolean {
  try {
    fs.rmSync(path.join(configDir, agentMcpConfigFilename(sessionId)), { force: true })
    return true
  } catch {
    return false
  }
}

/**
 * Delete every per-session config left in the directory, and report how many.
 *
 * Only ever called before this process has written one of its own — see
 * `AgentService`'s scratch sweep — because the files it deletes belong to
 * sessions of a previous run: a hard quit or a crash leaves the token on disk
 * with nothing tracking it. Matching on the prefix rather than clearing the
 * directory keeps the sweep away from anything else that lands in `agent-files`.
 */
export function sweepAgentMcpConfigs(configDir: string): number {
  return sweepScratch(configDir, (name) => name.startsWith(CONFIG_PREFIX) && name.endsWith(CONFIG_SUFFIX))
}

/**
 * Shared by the MCP-config and launcher-script sweeps: enumerate, filter,
 * unlink, and never throw. A sweep runs at startup and on the launch path, and
 * a scratch directory that cannot be read is not a reason to refuse to launch.
 */
export function sweepScratch(directory: string, matches: (name: string) => boolean): number {
  let removed = 0
  let entries: readonly string[]
  try {
    entries = fs.readdirSync(directory)
  } catch {
    return 0
  }
  for (const name of entries) {
    if (!matches(name)) {
      continue
    }
    try {
      fs.rmSync(path.join(directory, name), { force: true })
      removed += 1
    } catch {
      // Held open, or removed by another instance between readdir and unlink.
    }
  }
  return removed
}

/**
 * Session ids are generated by `core/id`, never renderer-supplied — but this
 * value becomes a filename, and a path separator arriving in one would write
 * the token somewhere other than the scratch directory. Cheap enough to be
 * unconditional rather than an assumption about a caller three layers away.
 *
 * Exported for the same reason {@link sweepScratch} is: every per-session
 * scratch file names itself this way, and a second copy of the rule is a second
 * chance to get it wrong.
 */
export function sanitizeSessionId(sessionId: string): string {
  return sessionId.replaceAll(/[^A-Za-z0-9_-]/g, "_")
}

/**
 * Substitute the concrete config path into a definition's `mcpConfigArgs`
 * template, replacing every `{path}` occurrence.
 *
 * One template syntax for both spellings the world uses: `--mcp-config {path}`
 * fills a path into its own argument, `--mcp-config={path}` splices it into an
 * existing one. No shell is involved on either side — this is argv composition.
 */
export function renderMcpConfigArgs(template: readonly string[], configPath: string): readonly string[] {
  return template.map((argument) => argument.replaceAll("{path}", configPath))
}
