import fs from "node:fs"
import path from "node:path"

/**
 * The one place every per-session scratch file's lifetime rules live.
 *
 * The MCP config, the session briefing, and the POSIX launcher script are all
 * files named for a session, written into the same APIWeave-owned directory,
 * and deleted by the same two triggers: the session's own terminal transition
 * (delete-one) and the startup sweep (delete-all-matching). Keeping the rules
 * here means the next scratch file kind gets the naming rule, the
 * best-effort-unlink shape, and the sweep for free instead of re-deriving each.
 */

/**
 * Session ids are generated by `core/id`, never renderer-supplied — but this
 * value becomes a filename, and a path separator arriving in one would write a
 * scratch file somewhere other than the scratch directory. Cheap enough to be
 * unconditional rather than an assumption about a caller three layers away.
 */
export function sanitizeSessionId(sessionId: string): string {
  return sessionId.replaceAll(/[^A-Za-z0-9_-]/g, "_")
}

/**
 * Drop one named scratch file. Best-effort by design: the caller is a terminal
 * state transition, and a session that already ended must not fail to be
 * recorded because a scratch file was already gone (or is held open on
 * Windows). Whatever survives here is reclaimed by the next startup sweep.
 */
export function deleteScratchFile(directory: string, filename: string): boolean {
  try {
    fs.rmSync(path.join(directory, filename), { force: true })
    return true
  } catch {
    return false
  }
}

/**
 * Write one scratch file and return its path. Every per-session scratch file
 * writes the same way: make the APIWeave-owned directory with `0o700`, write
 * the file with the given mode (`0o600` for anything carrying secrets or the
 * user's project names), and hand back the path.
 */
export function writeScratchFile(directory: string, filename: string, contents: string, fileMode: number): string {
  fs.mkdirSync(directory, { recursive: true, mode: 0o700 })
  const filePath = path.join(directory, filename)
  fs.writeFileSync(filePath, contents, { encoding: "utf8", mode: fileMode })
  return filePath
}

/**
 * The three operations every per-session scratch file kind needs — name one,
 * delete one, sweep all of a kind — parameterized by the filename
 * prefix/suffix that distinguishes the kinds.
 *
 * The MCP config (`apiweave-mcp-*.json`), the session briefing
 * (`briefing-*.md`), and the POSIX launcher script (`launch-*.command`) each
 * used to re-derive this trio around the shared {@link sweepScratch}; a
 * factory means the next kind gets the whole trio for the price of naming its
 * prefix and suffix.
 */
export function scratchFileKind(
  prefix: string,
  suffix: string,
): {
  readonly filename: (sessionId: string) => string
  readonly deleteOne: (directory: string, sessionId: string) => boolean
  readonly sweep: (directory: string) => number
} {
  const filename = (sessionId: string): string => `${prefix}${sanitizeSessionId(sessionId)}${suffix}`
  return {
    filename,
    deleteOne: (directory, sessionId) => deleteScratchFile(directory, filename(sessionId)),
    // Matching on the prefix/suffix rather than clearing the directory keeps
    // the sweep away from anything else that lands in the scratch directory.
    sweep: (directory) => sweepScratch(directory, (name) => name.startsWith(prefix) && name.endsWith(suffix)),
  }
}

/**
 * Enumerate, filter, unlink, and never throw. A sweep runs at startup and on
 * the launch path, and a scratch directory that cannot be read is not a reason
 * to refuse to launch.
 *
 * Only ever called before the process has written scratch files of its own —
 * see `AgentService`'s startup sweep — because the files it deletes belong to
 * sessions of a previous run: a hard quit or a crash leaves them on disk with
 * nothing tracking them.
 */
export function sweepScratch(directory: string, matches: (name: string) => boolean): number {
  let removed = 0
  let entries: readonly string[]
  try {
    entries = fs.readdirSync(directory)
  } catch {
    return 0
  }
  for (const name of entries) {
    if (!matches(name)) {
      continue
    }
    try {
      fs.rmSync(path.join(directory, name), { force: true })
      removed += 1
    } catch {
      // Held open, or removed by another instance between readdir and unlink.
    }
  }
  return removed
}
