import { describe, expect, it } from "vitest"
import { sanitizeSessionId } from "../scratch_files"

describe("sanitizeSessionId", () => {
  /**
   * The id is generated by `core/id`, never renderer-supplied — but it becomes
   * a filename, and a path separator arriving in one would write a scratch
   * file somewhere other than the scratch directory. The guard is cheap enough
   * to be unconditional rather than an assumption about a caller three layers
   * away.
   */
  it("strips path separators and traversal", () => {
    expect(sanitizeSessionId("../../etc/passwd")).not.toContain("/")
    expect(sanitizeSessionId("..\\..\\etc\\passwd")).not.toContain("\\")
    expect(sanitizeSessionId("..")).toBe("__")
    expect(sanitizeSessionId("../..")).toBe("_____")
    expect(sanitizeSessionId("a/b/c")).toBe("a_b_c")
  })

  it("keeps the characters a generated id actually uses", () => {
    expect(sanitizeSessionId("session_42-abcXYZ09")).toBe("session_42-abcXYZ09")
  })

  it("replaces anything else with an underscore, preserving length", () => {
    const hostile = 'a b:c"d*e?f<g>h|i'
    expect(sanitizeSessionId(hostile)).toBe("a_b_c_d_e_f_g_h_i")
    expect(sanitizeSessionId(hostile)).toHaveLength(hostile.length)
  })
})
