"""
Shared service layer for APIWeave backend.
All business logic lives here so both FastAPI routes and MCP tools call the same code.
"""

from app.services.collection_service import (
    add_workflow_to_collection,
    create_collection,
    delete_collection,
    export_collection,
    get_collection,
    list_collection_workflows,
    list_collections,
    remove_workflow_from_collection,
    update_collection,
)
from app.services.environment_service import (
    create_environment,
    delete_environment,
    duplicate_environment,
    get_environment,
    list_environments,
    list_environments_redacted,
    update_environment,
)
from app.services.import_service import (
    parse_curl_to_workflow,
    parse_har_to_workflow,
    parse_openapi_to_workflow,
)
from app.services.project_service import (
    create_project,
    delete_project,
    get_project,
    list_projects,
    update_project,
)
from app.services.run_service import (
    cancel_run,
    create_run,
    get_latest_failed_run,
    get_node_result,
    get_run,
    get_run_results,
    get_run_with_node_results,
    list_runs,
    trigger_workflow_run,
)
from app.services.scoped_workflow_service import (
    add_scoped_templates,
    clear_scoped_templates,
    create_scoped_workflow,
    delete_scoped_workflow,
    export_scoped_workflow,
    get_scoped_latest_failed_run,
    get_scoped_node_result,
    get_scoped_run_status,
    get_scoped_templates,
    get_scoped_workflow,
    import_scoped_curl,
    import_scoped_curl_dry_run,
    import_scoped_har,
    import_scoped_har_dry_run,
    import_scoped_openapi,
    import_scoped_openapi_dry_run,
    import_scoped_workflow,
    import_scoped_workflow_dry_run,
    list_scoped_runs,
    list_scoped_workflows,
    replace_scoped_templates,
    trigger_scoped_run,
    update_scoped_workflow,
)
from app.services.secret_sealed_box import (
    get_algorithm as get_sealed_box_algorithm,
)
from app.services.secret_sealed_box import (
    get_key_id as get_sealed_box_key_id,
)
from app.services.secret_sealed_box import (
    get_public_key_b64,
    open_sealed_box,
)
from app.services.secret_utils import (
    SecretMasker,
    detect_secrets_in_value,
    mask_log_value,
    mask_secrets_structural,
    sanitize_secrets_in_dict,
    serialize_document_for_export,
)
from app.services.workflow_service import (
    attach_to_collection,
    create_workflow,
    delete_workflow,
    export_workflow,
    get_workflow,
    import_workflow,
    import_workflow_dry_run,
    list_by_collection,
    list_unattached_workflows,
    list_workflows,
    update_workflow,
)
from app.services.workspace_service import (
    add_member,
    add_outside_collaborator,
    create_workspace,
    delete_workspace,
    get_workspace,
    get_workspace_by_slug,
    get_workspace_role,
    list_members,
    list_outside_collaborators,
    list_workspaces_for_org,
    list_workspaces_for_user,
    remove_member,
    remove_outside_collaborator,
    restore_workspace,
    update_member_role,
    update_workspace,
)

__all__ = [
    "list_workflows",
    "list_unattached_workflows",
    "get_workflow",
    "create_workflow",
    "update_workflow",
    "delete_workflow",
    "attach_to_collection",
    "list_by_collection",
    "export_workflow",
    "import_workflow",
    "import_workflow_dry_run",
    "create_run",
    "list_runs",
    "get_run",
    "cancel_run",
    "get_run_with_node_results",
    "get_node_result",
    "get_run_results",
    "get_latest_failed_run",
    "trigger_workflow_run",
    "list_environments",
    "get_environment",
    "create_environment",
    "update_environment",
    "delete_environment",
    "duplicate_environment",
    "list_environments_redacted",
    "list_collections",
    "get_collection",
    "create_collection",
    "update_collection",
    "delete_collection",
    "add_workflow_to_collection",
    "remove_workflow_from_collection",
    "list_collection_workflows",
    "export_collection",
    "parse_curl_to_workflow",
    "parse_har_to_workflow",
    "parse_openapi_to_workflow",
    "detect_secrets_in_value",
    "mask_log_value",
    "mask_secrets_structural",
    "sanitize_secrets_in_dict",
    "serialize_document_for_export",
    "SecretMasker",
    "get_public_key_b64",
    "get_sealed_box_key_id",
    "get_sealed_box_algorithm",
    "open_sealed_box",
    # Workspace services
    "create_workspace",
    "get_workspace",
    "get_workspace_by_slug",
    "update_workspace",
    "delete_workspace",
    "restore_workspace",
    "list_workspaces_for_user",
    "list_workspaces_for_org",
    "add_member",
    "update_member_role",
    "remove_member",
    "list_members",
    "add_outside_collaborator",
    "remove_outside_collaborator",
    "list_outside_collaborators",
    "get_workspace_role",
    # Project services
    "create_project",
    "get_project",
    "update_project",
    "delete_project",
    "list_projects",
    # Scoped workflow services
    "create_scoped_workflow",
    "get_scoped_workflow",
    "update_scoped_workflow",
    "delete_scoped_workflow",
    "list_scoped_workflows",
    "list_scoped_runs",
    "trigger_scoped_run",
    "get_scoped_latest_failed_run",
    "get_scoped_run_status",
    "get_scoped_node_result",
    "export_scoped_workflow",
    "import_scoped_workflow",
    "import_scoped_workflow_dry_run",
    "import_scoped_har",
    "import_scoped_har_dry_run",
    "import_scoped_openapi",
    "import_scoped_openapi_dry_run",
    "import_scoped_curl",
    "import_scoped_curl_dry_run",
    "get_scoped_templates",
    "add_scoped_templates",
    "replace_scoped_templates",
    "clear_scoped_templates",
]
